/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Carousel: typeof import('primevue/carousel')['default']
    EducationSection: typeof import('./src/components/LifeJourney.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LifeJourney: typeof import('./src/components/LifeJourney.vue')['default']
    MainPanel: typeof import('./src/components/MainPanel.vue')['default']
    MLProjects: typeof import('./src/components/MLProjects.vue')['default']
    ScorpioIcon: typeof import('./src/components/icons/ScorpioIcon.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    Slider: typeof import('primevue/slider')['default']
    UBCVlog: typeof import('./src/components/UBCVlog.vue')['default']
  }
}
