/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EducationSection: typeof import('./src/components/LifeJourney.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LifeJourney: typeof import('./src/components/LifeJourney.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
  }
}
